// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.Entity_Framework;

#nullable disable

namespace Repositories.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240129151048_DbContext_mis_a_jour")]
    partial class DbContext_mis_a_jour
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Anonymous", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<int?>("GenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("GenderId");

                    b.ToTable("Anonymouses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 18
                        },
                        new
                        {
                            Id = 2,
                            Age = 60
                        },
                        new
                        {
                            Id = 3,
                            Age = 36
                        },
                        new
                        {
                            Id = 4,
                            Age = 42
                        });
                });

            modelBuilder.Entity("Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnonymousId")
                        .HasColumnType("int");

                    b.Property<int>("ChoiceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Horodatage")
                        .HasColumnType("datetime2");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousId");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Entities.Choice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Choices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Yes",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 2,
                            Label = "No",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 3,
                            Label = "Unconcerned",
                            QuestionId = 1
                        },
                        new
                        {
                            Id = 4,
                            Label = "0",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 5,
                            Label = "1",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 6,
                            Label = "2",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 7,
                            Label = "3",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 8,
                            Label = "4",
                            QuestionId = 2
                        },
                        new
                        {
                            Id = 9,
                            Label = "5",
                            QuestionId = 2
                        });
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Afghanistan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Albania"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Algeria"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Andorra"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Angola"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Antigua"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Armenia"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Australia"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Austria"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Azerbaijan"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Bahamas"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Bahrain"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Bangladesh"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Barbados"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Belarus"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Belgium"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Belize"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Benin"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Bhutan"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Bolivia"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Bosnia"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Botswana"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Brazil"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Brunei Darussalam"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Bulgaria"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Burkina Faso"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Burundi"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Cambodia"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Cameroon"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Canada"
                        },
                        new
                        {
                            Id = 32,
                            Name = "Cape Verde"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Central African Republic"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Chad"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Chile"
                        },
                        new
                        {
                            Id = 36,
                            Name = "China"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Colombia"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Comoros"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Congo (Republic of the)"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Costa Rica"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Côte d’Ivoire"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Croatia"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Cuba"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Cyprus"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Czech RepubliC"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Democratic People’s Republic of Korea"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Democratic Republic of the Congo"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Denmark"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Djibouti"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Dominica"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Dominican Republic"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Ecuador"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Egypt"
                        },
                        new
                        {
                            Id = 54,
                            Name = "El Salvador"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Equatorial Guinea"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Eritrea"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Estonia"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Ethiopia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Fiji"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Finland"
                        },
                        new
                        {
                            Id = 61,
                            Name = "France"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Gabon"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Gambia"
                        },
                        new
                        {
                            Id = 64,
                            Name = "Georgia"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Germany"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Ghana"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Greece"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Grenada"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Guatemala"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Guinea"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Guinea-Bissau"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Guyana"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Haiti"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Honduras"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Hungary"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Iceland"
                        },
                        new
                        {
                            Id = 77,
                            Name = "India"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Indonesia"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Iran"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Iraq"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Ireland"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Israel"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Italy"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Jamaica"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Japan"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Jordan"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Kazakhstan"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Kenya"
                        },
                        new
                        {
                            Id = 89,
                            Name = "Kiribati"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Kuwait"
                        },
                        new
                        {
                            Id = 91,
                            Name = "Kyrgyzstan"
                        },
                        new
                        {
                            Id = 92,
                            Name = "Lao People's Democratic Republic"
                        },
                        new
                        {
                            Id = 93,
                            Name = "Latvia"
                        },
                        new
                        {
                            Id = 94,
                            Name = "Lebanon"
                        },
                        new
                        {
                            Id = 95,
                            Name = "Lesotho"
                        },
                        new
                        {
                            Id = 96,
                            Name = "Liberia"
                        },
                        new
                        {
                            Id = 97,
                            Name = "Libya"
                        },
                        new
                        {
                            Id = 98,
                            Name = "Liechtenstein"
                        },
                        new
                        {
                            Id = 99,
                            Name = "Lithuania"
                        },
                        new
                        {
                            Id = 100,
                            Name = "Luxembourg"
                        },
                        new
                        {
                            Id = 101,
                            Name = "Madagascar"
                        },
                        new
                        {
                            Id = 102,
                            Name = "Malawi"
                        },
                        new
                        {
                            Id = 103,
                            Name = "Malaysia"
                        },
                        new
                        {
                            Id = 104,
                            Name = "Maldives"
                        },
                        new
                        {
                            Id = 105,
                            Name = "Mali"
                        },
                        new
                        {
                            Id = 106,
                            Name = "Malta"
                        },
                        new
                        {
                            Id = 107,
                            Name = "Marshall Islands"
                        },
                        new
                        {
                            Id = 108,
                            Name = "Mauritania"
                        },
                        new
                        {
                            Id = 109,
                            Name = "Mauritius"
                        },
                        new
                        {
                            Id = 110,
                            Name = "Mexico"
                        },
                        new
                        {
                            Id = 111,
                            Name = "Micronesia (Federated States of)"
                        },
                        new
                        {
                            Id = 112,
                            Name = "Monaco"
                        },
                        new
                        {
                            Id = 113,
                            Name = "Mongolia"
                        },
                        new
                        {
                            Id = 114,
                            Name = "Montenegro"
                        },
                        new
                        {
                            Id = 115,
                            Name = "Morocco"
                        },
                        new
                        {
                            Id = 116,
                            Name = "Mozambique"
                        },
                        new
                        {
                            Id = 117,
                            Name = "Myanmar"
                        },
                        new
                        {
                            Id = 118,
                            Name = "Namibia"
                        },
                        new
                        {
                            Id = 119,
                            Name = "Nauru"
                        },
                        new
                        {
                            Id = 120,
                            Name = "Nepal"
                        },
                        new
                        {
                            Id = 121,
                            Name = "Netherlands"
                        },
                        new
                        {
                            Id = 122,
                            Name = "New Zealand"
                        },
                        new
                        {
                            Id = 123,
                            Name = "Nicaragua"
                        },
                        new
                        {
                            Id = 124,
                            Name = "Niger"
                        },
                        new
                        {
                            Id = 125,
                            Name = "Nigeria"
                        },
                        new
                        {
                            Id = 126,
                            Name = "Norway"
                        },
                        new
                        {
                            Id = 127,
                            Name = "Oman"
                        },
                        new
                        {
                            Id = 128,
                            Name = "Pakistan"
                        },
                        new
                        {
                            Id = 129,
                            Name = "Palau"
                        },
                        new
                        {
                            Id = 130,
                            Name = "Panama"
                        },
                        new
                        {
                            Id = 131,
                            Name = "Papua New Guinea"
                        },
                        new
                        {
                            Id = 132,
                            Name = "Paraguay"
                        },
                        new
                        {
                            Id = 133,
                            Name = "Peru"
                        },
                        new
                        {
                            Id = 134,
                            Name = "Philippines"
                        },
                        new
                        {
                            Id = 135,
                            Name = "Poland"
                        },
                        new
                        {
                            Id = 136,
                            Name = "Portugal"
                        },
                        new
                        {
                            Id = 137,
                            Name = "Qatar"
                        },
                        new
                        {
                            Id = 138,
                            Name = "Republic of Korea"
                        },
                        new
                        {
                            Id = 139,
                            Name = "Republic of Moldova"
                        },
                        new
                        {
                            Id = 140,
                            Name = "Romania"
                        },
                        new
                        {
                            Id = 141,
                            Name = "Russian Federation"
                        },
                        new
                        {
                            Id = 142,
                            Name = "Rwanda"
                        },
                        new
                        {
                            Id = 143,
                            Name = "Saint Kitts and Nevis"
                        },
                        new
                        {
                            Id = 144,
                            Name = "Saint Lucia"
                        },
                        new
                        {
                            Id = 145,
                            Name = "Saint Vincent and the Grenadines"
                        },
                        new
                        {
                            Id = 146,
                            Name = "Samoa"
                        },
                        new
                        {
                            Id = 147,
                            Name = "San Marino"
                        },
                        new
                        {
                            Id = 148,
                            Name = "Sao Tome and Principe"
                        },
                        new
                        {
                            Id = 149,
                            Name = "Saudi Arabia"
                        },
                        new
                        {
                            Id = 150,
                            Name = "Senegal"
                        },
                        new
                        {
                            Id = 151,
                            Name = "Serbia"
                        },
                        new
                        {
                            Id = 152,
                            Name = "Seychelles"
                        },
                        new
                        {
                            Id = 153,
                            Name = "Sierra Leone"
                        },
                        new
                        {
                            Id = 154,
                            Name = "Singapore"
                        },
                        new
                        {
                            Id = 155,
                            Name = "Slovakia"
                        },
                        new
                        {
                            Id = 156,
                            Name = "Slovenia"
                        },
                        new
                        {
                            Id = 157,
                            Name = "Solomon Islands"
                        },
                        new
                        {
                            Id = 158,
                            Name = "Somalia"
                        },
                        new
                        {
                            Id = 159,
                            Name = "South Africa"
                        },
                        new
                        {
                            Id = 160,
                            Name = "Spain"
                        },
                        new
                        {
                            Id = 161,
                            Name = "Sri Lanka"
                        },
                        new
                        {
                            Id = 162,
                            Name = "Sudan"
                        },
                        new
                        {
                            Id = 163,
                            Name = "Suriname"
                        },
                        new
                        {
                            Id = 164,
                            Name = "Swaziland"
                        },
                        new
                        {
                            Id = 165,
                            Name = "Switzerland"
                        },
                        new
                        {
                            Id = 166,
                            Name = "Sweden"
                        },
                        new
                        {
                            Id = 167,
                            Name = "Syria"
                        },
                        new
                        {
                            Id = 168,
                            Name = "Tajikistan"
                        },
                        new
                        {
                            Id = 169,
                            Name = "Thailand"
                        },
                        new
                        {
                            Id = 170,
                            Name = "The former Yugoslav Republic of Macedonia"
                        },
                        new
                        {
                            Id = 171,
                            Name = "Timor Leste"
                        },
                        new
                        {
                            Id = 172,
                            Name = "Togo"
                        },
                        new
                        {
                            Id = 173,
                            Name = "Tonga"
                        },
                        new
                        {
                            Id = 174,
                            Name = "Trinidad and Tobago"
                        },
                        new
                        {
                            Id = 175,
                            Name = "Tunisia"
                        },
                        new
                        {
                            Id = 176,
                            Name = "Turkey"
                        },
                        new
                        {
                            Id = 177,
                            Name = "Turkmenistan"
                        },
                        new
                        {
                            Id = 178,
                            Name = "Tuvalu"
                        },
                        new
                        {
                            Id = 179,
                            Name = "Uganda"
                        },
                        new
                        {
                            Id = 180,
                            Name = "Ukraine"
                        },
                        new
                        {
                            Id = 181,
                            Name = "United Arab Emirates"
                        },
                        new
                        {
                            Id = 182,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 183,
                            Name = "United of Republic of Tanzania"
                        },
                        new
                        {
                            Id = 184,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 185,
                            Name = "Uruguay"
                        },
                        new
                        {
                            Id = 186,
                            Name = "Uzbekistan"
                        },
                        new
                        {
                            Id = 187,
                            Name = "Vanuatu"
                        },
                        new
                        {
                            Id = 188,
                            Name = "Venezuela"
                        },
                        new
                        {
                            Id = 189,
                            Name = "Viet Nam"
                        },
                        new
                        {
                            Id = 190,
                            Name = "Yemen"
                        },
                        new
                        {
                            Id = 191,
                            Name = "Zambia"
                        },
                        new
                        {
                            Id = 192,
                            Name = "Zimbabwe"
                        });
                });

            modelBuilder.Entity("Entities.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int?>("TimerCDId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("UserPersonId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TimerCDId");

                    b.HasIndex("UserPersonId");

                    b.ToTable("Forms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Questions about cities",
                            StatusId = 1,
                            Title = "Europeans Capitals",
                            UserPersonId = "981173f4-7557-4cde-b839-1ac488b30f9f"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Questions about cities v2",
                            StatusId = 2,
                            Title = "Europeans Capitals",
                            UserPersonId = "951173f4-7557-4cde-b839-1ac488b30f9f"
                        });
                });

            modelBuilder.Entity("Entities.Gender", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "Woman"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Man"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Other"
                        });
                });

            modelBuilder.Entity("Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TimerCDId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("TimerCDId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Choose one answer",
                            FormId = 2,
                            Label = "Do you like Paris ?"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Choose one answer",
                            FormId = 2,
                            Label = "How much?",
                            TimerCDId = 1
                        });
                });

            modelBuilder.Entity("Entities.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Statuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Label = "In progress"
                        },
                        new
                        {
                            Id = 2,
                            Label = "Validated"
                        },
                        new
                        {
                            Id = 3,
                            Label = "Archived"
                        });
                });

            modelBuilder.Entity("Entities.TimerCD", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountDown")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Timers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountDown = 30
                        },
                        new
                        {
                            Id = 2,
                            CountDown = 60
                        },
                        new
                        {
                            Id = 3,
                            CountDown = 90
                        },
                        new
                        {
                            Id = 4,
                            CountDown = 120
                        });
                });

            modelBuilder.Entity("Entities.UserPerson", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("ChoiceId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("LastName")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChoiceId");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "951173f4-7557-4cde-b839-1ac488b30f9f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "514a216a-0c07-4ca1-bae7-25b389afc715",
                            DateOfBirth = new DateOnly(1991, 12, 25),
                            Email = "example@example.com",
                            EmailConfirmed = true,
                            FirstName = "Michel",
                            LastName = "Does",
                            LockoutEnabled = false,
                            NormalizedEmail = "EXAMPLE@EXAMPLE.COM",
                            NormalizedUserName = "EXAMPLE@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEtM0G8yJiz5QPiNu4bkpQyhQcMtPWB0EkxiCNV2IGqjriKU7WLoDwvBr6uCjH1+Fg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2EKLCF5HV2AN7DRFWTAEU5A5MCQ2OOYX",
                            TwoFactorEnabled = false,
                            UserName = "example@example.com"
                        },
                        new
                        {
                            Id = "981173f4-7557-4cde-b839-1ac488b30f9f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ce3e6bf0-1a0b-4f5b-8822-9165d907c101",
                            DateOfBirth = new DateOnly(1991, 12, 25),
                            Email = "john.doe@example.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a4dd2916-9b82-4c60-b552-e7fe605b2fcf",
                            TwoFactorEnabled = false,
                            UserName = "JohnDoe"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Entities.Anonymous", b =>
                {
                    b.HasOne("Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Entities.Gender", "Gender")
                        .WithMany("Anonymous")
                        .HasForeignKey("GenderId");

                    b.Navigation("Country");

                    b.Navigation("Gender");
                });

            modelBuilder.Entity("Entities.Answer", b =>
                {
                    b.HasOne("Entities.Anonymous", "Anonymous")
                        .WithMany()
                        .HasForeignKey("AnonymousId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Choice", "Choice")
                        .WithMany()
                        .HasForeignKey("ChoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anonymous");

                    b.Navigation("Choice");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Entities.Choice", b =>
                {
                    b.HasOne("Entities.Question", "Question")
                        .WithMany("Choices")
                        .HasForeignKey("QuestionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Entities.Form", b =>
                {
                    b.HasOne("Entities.Status", "Status")
                        .WithMany("Forms")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.TimerCD", "TimerCD")
                        .WithMany("Forms")
                        .HasForeignKey("TimerCDId");

                    b.HasOne("Entities.UserPerson", "UserPerson")
                        .WithMany("Forms")
                        .HasForeignKey("UserPersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("TimerCD");

                    b.Navigation("UserPerson");
                });

            modelBuilder.Entity("Entities.Question", b =>
                {
                    b.HasOne("Entities.Form", "Form")
                        .WithMany("Questions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.TimerCD", "TimerCD")
                        .WithMany("Questions")
                        .HasForeignKey("TimerCDId");

                    b.Navigation("Form");

                    b.Navigation("TimerCD");
                });

            modelBuilder.Entity("Entities.UserPerson", b =>
                {
                    b.HasOne("Entities.Choice", null)
                        .WithMany("UserPersons")
                        .HasForeignKey("ChoiceId");

                    b.HasOne("Entities.Country", null)
                        .WithMany("UserPersons")
                        .HasForeignKey("CountryId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.UserPerson", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.UserPerson", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.UserPerson", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.UserPerson", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Choice", b =>
                {
                    b.Navigation("UserPersons");
                });

            modelBuilder.Entity("Entities.Country", b =>
                {
                    b.Navigation("UserPersons");
                });

            modelBuilder.Entity("Entities.Form", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Entities.Gender", b =>
                {
                    b.Navigation("Anonymous");
                });

            modelBuilder.Entity("Entities.Question", b =>
                {
                    b.Navigation("Choices");
                });

            modelBuilder.Entity("Entities.Status", b =>
                {
                    b.Navigation("Forms");
                });

            modelBuilder.Entity("Entities.TimerCD", b =>
                {
                    b.Navigation("Forms");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Entities.UserPerson", b =>
                {
                    b.Navigation("Forms");
                });
#pragma warning restore 612, 618
        }
    }
}
